/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataMapping: typeof import('./src/components/data-mapping.vue')['default']
    NormalContent: typeof import('./src/components/normal-content.vue')['default']
    PortMapping: typeof import('./src/components/port-mapping.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
